# Generated by Django 4.1.5 on 2023-01-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cell_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'ordering': ('x', 'y')},
        ),
        migrations.AlterModelOptions(
            name='worldcell',
            options={'ordering': ('cell__x', 'cell__y')},
        ),
        migrations.AlterField(
            model_name='world',
            name='name',
            field=models.CharField(default='Test', max_length=200, verbose_name='Название'),
        ),
    ]
